### ISSUE TITLE
error occurred while finetuning 

### ISSUE THREAD

**Issue by YuyangQian** [Melmaphother/TimeDART#1]
Hi, this model is a great work, but i met a problem.
I followed the instructions in readme, and here is what ocurred when executing sh scripts/finetune/ETTh2.sh

>>>>>>>start training : finetune_TimeDART_ETTh2_M_il336_ll48_pl96_dm8_df32_nh8_el2_dl1_fc1_dp0.4_hdp0.1_ep10_bs16_lr0.0001>>>>>>>>>>>>>>>>>>>>>>>>>>
<class 'numpy.ndarray'>
(8640, 7)
train 8209 513
<class 'numpy.ndarray'>
(3216, 7)
val 2785 174
<class 'numpy.ndarray'>
(3216, 7)
test 2785 2785
Training:   0%|                                                                                                                                                                                                | 0/513 [00:00<?, ?it/s]C
urrent learning rate: 0.0000040
Training: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 513/513 [00:13<00:00, 37.15it/s]
.
.
.
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2785/2785 [00:08<00:00, 339.77it/s]
Epoch: 10, Steps: 513, Time: 26.58s | Train Loss: 0.4172925 Vali Loss: 0.2198206 Test Loss: 0.2786267
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : finetune_TimeDART_ETTh2_M_il336_ll48_pl96_dm8_df32_nh8_el2_dl1_fc1_dp0.4_hdp0.1_ep10_bs16_lr0.0001<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<class 'numpy.ndarray'>
(3216, 7)
test 2785 2785
Traceback (most recent call last):
  File "run.py", line 264, in <module>
    main()
  File "run.py", line 260, in main
    exp.test()
  File "S:\Pycharm\projects\TimeDART-main\exp\exp_timedart.py", line 369, in test
    preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])
IndexError: tuple index out of range

Should I change the parameter  --features M to --features MS

**Comment by Melmaphother** [comment]
Thank you for your attention to our work.

Regarding your question, if I understood correctly, it seems that an error occurs during the final testing after fine-tuning:

```python
preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])
IndexError: tuple index out of range
```

When I tested it locally, the output at this point looked like this, which you might find helpful as a reference: 
<img width="873" alt="TimeDART-issue-1" src="https://github.com/user-attachments/assets/cb23342e-f5ce-473f-a197-794c4d37005a">

You could check if any part of the code was modified. If you haven’t made any changes, you can print out the shape of `preds` and examine the details to pinpoint where the issue might be.

**Comment by YuyangQian** [comment]
Thank you for your reply!
In exp_timedart.py, line: 367, I added 
        preds = np.array(preds)
        trues = np.array(trues)
        print("Original preds shape:", preds.shape)
        print("Original trues shape:", trues.shape
And the result shows 
        Original preds shape: (2785,)
        Original trues shape: (2785,)
I didn't change anything of the original project

**Comment by YuyangQian** [comment]
I changed the code In exp_timedart.py, line: 362

                preds.append(pred)    ->    preds.append(pred.numpy())
                trues.append(true)      ->    trues.append(true.numpy())
               
And it works. Thanks for your reply!
